### ISSUE TITLE
Merge com o Saia de Casa

### ISSUE THREAD

**Issue by woliveiras** [theandersonn/agenda-dev#2]
@theandersonn, não rola um Merge com esse pessoal aqui? 

https://github.com/saiadecasa/saiadecasa.github.io

**Comment by theandersonn** [comment]
@woliveiras Sim, abolutamente sim.

Não sei se o @rogeriopradoj tem interesse. 
Na verdade esse repositório é uma espécia de rascunho que eu intencionava fazer; pelo fato de ser bem simples, tem facilitado a inclusão rápida de eventos.

Sempre que posso participo com a indição de eventos no SaiaDeCasa.

**Comment by woliveiras** [comment]
Aaaa, da hora cara! 

Então, era só a ideia de pegar sua lista e jogar tudo lá pra centralizar as informações mesmo. :smile:

**Comment by theandersonn** [comment]
Entendi, super válido.
Obrigado pela sugestão :)

**Comment by woliveiras** [comment]
😄
